CREATE TABLE `nordblog`.`user` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `display_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT now(),
  `edited_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);
